### ISSUE TITLE
Add notification remind user to go to sleep

### ISSUE THREAD

**Issue by hungvu193** [letelete/Sleep-Cycle-Alarm#120]
I think that 's a good idea if there 's a notification to remind user to go to sleep, that notification will have some features like prevent all notifications until user woke up :D
(https://github.com/Fewlaps/quitnow-sleep-time)

**Comment by letelete** [comment]
Your proposal seems to be really helpful, however, I don't maintain this project anymore, since It was my very first Android app and has lots of bugs and code is kinda messy. So it was a testing field rather than a serious project. Nonetheless, you can work on this issue if you want :octocat:

**Comment by hungvu193** [comment]
😂 okay, i will try :D
